name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '15 19 * * 6' # 週末
    - cron: '50 0 * * 1'  # 假搓合
    - cron: '30 1 * * 1'  # 盤中
    - cron: '40 5 * * 1'  # 盤後
    - cron: '0 8 * * 1'   # 收盤

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-java@v2
        with:
          distribution: adopt
          java-version: 11

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Build conventions
        run: ./gradlew -p ./fugle-kt-conventions build

      - name: Build library
        run: ./gradlew build

      - name: Run integration tests
        run: ./gradlew integrationTest
        env:
          FUGLE_TOKEN: ${{ secrets.FUGLE_TOKEN }}
