name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-java@v2
        with:
          distribution: adopt
          java-version: 11

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Build conventions
        run: ./gradlew -p ./fugle-kt-conventions build

      - name: Build library
        run: ./gradlew build

      - name: Run integration tests
        run: ./gradlew integrationTest
        env:
          FUGLE_TOKEN: ${{ secrets.FUGLE_TOKEN }}
